# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cocoafish"
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wei Kong"]
  s.date = "2011-11-17"
  s.description = "Ruby client to access Cocoafish"
  s.email = "wei@cocoafish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "./Gemfile",
    "./Gemfile.lock",
    "./LICENSE.txt",
    "./README.rdoc",
    "./Rakefile",
    "./VERSION",
    "./cocoafish.gemspec",
    "lib/cocoafish.rb",
    "lib/cocoafish/client.rb",
    "lib/cocoafish/cocoafish_object.rb",
    "lib/cocoafish/connection.rb",
    "lib/cocoafish/endpoint.rb",
    "lib/cocoafish/objectified_hash.rb"
  ]
  s.homepage = "http://github.com/cocoafish"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Cocoafish Ruby Client"
  s.test_files = [
    "test/helper.rb",
    "test/test_cocoafish.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<simple_oauth>, ["~> 0.1.4"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.6"])
      s.add_runtime_dependency(%q<simple_oauth>, ["~> 0.1.4"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.6"])
      s.add_dependency(%q<simple_oauth>, ["~> 0.1.4"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.6"])
      s.add_dependency(%q<simple_oauth>, ["~> 0.1.4"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.6"])
    s.add_dependency(%q<simple_oauth>, ["~> 0.1.4"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.6"])
    s.add_dependency(%q<simple_oauth>, ["~> 0.1.4"])
  end
end

